name: mruby on YABM CI

on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: yamori813/rtl819x-toolchain
    - uses: actions/cache@v4
      with:
        path: rtl819x-toolchain
        key: rtl819x-toolchain

