name: mruby on YABM CI

on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v5
      with:
        path: rtlbm-mruby
    - name: Checkout tools repo
      uses: actions/checkout@v5
      with:
        repository: yamori813/rtl819x-toolchain
        path: rtl819x-toolchain
    - name: install 32bit libz.so.1
      run: sudo apt-get install lib32z1
    - name: Cache build/work
      uses: actions/cache@v3
      with:
        path: rtlbm-mruby/build/work
        key: ${{ runner.os }}-build-work
        restore-keys: |
          ${{ runner.os }}-
#    - name: check lib
#      run: find /usr/lib -name libz.so.1;ldconfig -p | grep libz
#    - name: dir
#      run: ls -l ${RUNNER_WORKSPACE}/rtlbm-mruby/;pwd;uname -s
    - name: get files
      run: cd rtlbm-mruby/build;./getfiles.sh
    - name: make newlib
      run: cd rtlbm-mruby/build;./mknewlib.sh
    - name: make lwip
      run: cd rtlbm-mruby/build;./mklwip.sh
    - name: make bearssl
      run: cd rtlbm-mruby/build;./mkbearssl.sh
    - name: make mruby
      run: cd rtlbm-mruby/build;./mkmruby.sh
    - name: make allvm
      run: cd rtlbm-mruby;./mkallvm.sh
    - name: Archive vm files
      uses: actions/upload-artifact@v4
      with:
        path: rtlbm-mruby/*.rtl

